// GENERATED — never hand-edit.
// Source: apps/api Nest controllers + DTOs via openapi.json.
// Regenerate: pnpm --filter @mealplan/contracts-api run gen. CI gate: pnpm --filter @mealplan/contracts-api run check.
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness. The process is up; says nothing about its dependencies. */
        get: operations["AppController_healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness: database reachable, auth verifier configured. */
        get: operations["AppController_readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts-probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inert fixture proving apps/api compiles against @mealplan/contracts. */
        get: operations["AppController_contractsProbe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/households": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the households I belong to
         * @description Scoped by membership. There is no route that lists households the caller is not in.
         */
        get: operations["HouseholdsController_listMine"];
        put?: never;
        /**
         * Create a household
         * @description The caller becomes its first planner. Not a parameter: a household with no planner could never be administered.
         */
        post: operations["HouseholdsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/households/{householdId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one household with its members */
        get: operations["HouseholdsController_get"];
        put?: never;
        post?: never;
        /**
         * Delete a household
         * @description Memberships cascade. The audit trail does not — the record that it was deleted outlives it.
         */
        delete: operations["HouseholdsController_remove"];
        options?: never;
        head?: never;
        /** Rename a household */
        patch: operations["HouseholdsController_rename"];
        trace?: never;
    };
    "/households/{householdId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List members of a household */
        get: operations["HouseholdsController_listMembers"];
        put?: never;
        /**
         * Add a member to a household
         * @description Omit userId to create a PLACEHOLDER — a real member with no account yet, which is the normal path: a household must be plannable before everyone has signed up. Send userId only when the caller already knows the account id.
         */
        post: operations["HouseholdsController_addMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/households/{householdId}/members/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Leave a household
         * @description Any member may remove their own membership. A sole planner cannot — promote someone first.
         */
        delete: operations["HouseholdsController_leave"];
        options?: never;
        head?: never;
        /**
         * Edit my own display name or linked person
         * @description Your profile is yours: a planner cannot change it for you, and this route cannot change your role.
         */
        patch: operations["HouseholdsController_updateOwnMembership"];
        trace?: never;
    };
    "/households/{householdId}/members/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a member from a household */
        delete: operations["HouseholdsController_removeMember"];
        options?: never;
        head?: never;
        /**
         * Change another member's role, or edit a placeholder
         * @description A placeholder member (userId null) is fully editable by a planner. A member who has an account is role-only — their profile is theirs.
         */
        patch: operations["HouseholdsController_updateMember"];
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The verified caller and their household memberships */
        get: operations["MeController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ReadyzResponse: {
            /** @description True when every dependency below is healthy. */
            ok: boolean;
            /** @description Database reachable (SELECT 1 succeeded). */
            database: boolean;
            /**
             * @description How access tokens are verified. "jwks" is the production posture — this service holds no signing material.
             * @enum {string}
             */
            authMode: "jwks" | "shared-secret";
        };
        CreateHouseholdRequest: {
            /**
             * @description Household name.
             * @example The Germanos
             */
            name: string;
            /**
             * @description The creator's own human-readable name in this household. Required because every member has one — a member list of UUIDs is not a member list.
             * @example Devon
             */
            displayName: string;
            /**
             * @description Which person in the library the creator eats as. Omit if the creator plans but does not eat.
             * @example devon
             */
            personName?: string;
        };
        HouseholdMemberView: {
            /** Format: uuid */
            id: string;
            /** @description Human-readable name. Always present. */
            displayName: string;
            /** @enum {string} */
            role: "planner" | "cook" | "eater";
            /**
             * Format: uuid
             * @description auth.users id, or null when this member is a PLACEHOLDER — a real member with no account yet. Null here is the one flag that distinguishes the two kinds of member; a placeholder can never be a caller.
             */
            userId: Record<string, never> | null;
            /** @description Library person key, or null if this member does not eat. */
            personName: Record<string, never> | null;
            /** @description Invite intent for a placeholder. Always null once the member has an account. */
            inviteEmail: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
        };
        HouseholdDetail: {
            /** Format: uuid */
            id: string;
            name: string;
            members: components["schemas"]["HouseholdMemberView"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ApiErrorDetail: {
            /**
             * @description Dotted path of the offending field.
             * @example name
             */
            field: string;
            /** @description What is wrong with it. */
            message: string;
        };
        ApiErrorBody: {
            /**
             * @description Machine-readable code. Switch on this.
             * @enum {string}
             */
            code: "unauthenticated" | "forbidden" | "not_found" | "validation_failed" | "conflict" | "internal";
            /** @description Human-readable summary. Not a stable contract. */
            message: string;
            /** @description Per-field detail. Present on validation_failed; every failing field is reported, not just the first. */
            details?: components["schemas"]["ApiErrorDetail"][];
        };
        ApiErrorResponse: {
            error: components["schemas"]["ApiErrorBody"];
            /**
             * @description Correlates this response with the server log line. Quote it in bug reports.
             * @example 3f1c0b5e-9a1f-4a1d-9a2f-6b0c9c8f0a11
             */
            requestId: string;
        };
        HouseholdSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            /**
             * @description The CALLER's role here.
             * @enum {string}
             */
            role: "planner" | "cook" | "eater";
            /** @description The CALLER's display name here. */
            displayName: string;
            /** @description The CALLER's library person key here. */
            personName: Record<string, never> | null;
            /** @description Members in this household, including placeholders and the caller. */
            memberCount: number;
            /** Format: date-time */
            createdAt: string;
        };
        UpdateHouseholdRequest: {
            name: string;
        };
        AddHouseholdMemberRequest: {
            /**
             * @description This member's human-readable name.
             * @example Alex
             */
            displayName: string;
            /** @enum {string} */
            role: "planner" | "cook" | "eater";
            /**
             * Format: uuid
             * @description auth.users id, when the caller already knows it. Omit to create a placeholder member with no account.
             */
            userId?: string;
            /**
             * @description The library person this member eats as.
             * @example alex
             */
            personName?: string;
            /**
             * Format: email
             * @description Where an invitation WOULD be sent once that flow exists. Stored as intent only: it is never checked against the account directory, so sending it reveals nothing about whether an account exists. Rejected on a member that already has an account.
             */
            inviteEmail?: string;
        };
        UpdateOwnMembershipRequest: {
            displayName?: string;
            /**
             * @description The library person you eat as. Send null to stop eating in this plan.
             * @example devon
             */
            personName?: Record<string, never> | null;
        };
        UpdateHouseholdMemberRequest: {
            /** @enum {string} */
            role?: "planner" | "cook" | "eater";
            /** @description Placeholder members only. */
            displayName?: string;
            /**
             * @description Placeholder members only. Send null to unlink the member from the plan.
             * @example alex
             */
            personName?: Record<string, never> | null;
            /**
             * Format: email
             * @description Placeholder members only. Send null to clear.
             */
            inviteEmail?: Record<string, never> | null;
        };
        MeResponse: {
            /**
             * Format: uuid
             * @description auth.users id of the verified caller.
             */
            userId: string;
            email: Record<string, never> | null;
            isAnonymous: boolean;
            /** @description Every household the caller belongs to. */
            households: components["schemas"]["HouseholdSummary"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AppController_readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyzResponse"];
                };
            };
            /** @description Database unreachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyzResponse"];
                };
            };
        };
    };
    AppController_contractsProbe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HouseholdsController_listMine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseholdSummary"][];
                };
            };
            /** @description Validation failed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    HouseholdsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateHouseholdRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseholdDetail"];
                };
            };
            /** @description Validation failed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    HouseholdsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseholdDetail"];
                };
            };
            /** @description Validation failed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description You are a member, but your role is below what this route requires. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description No such household, OR you are not a member of it. Deliberately indistinguishable. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    HouseholdsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description You are a member, but your role is below what this route requires. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description No such household, OR you are not a member of it. Deliberately indistinguishable. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    HouseholdsController_rename: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateHouseholdRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseholdDetail"];
                };
            };
            /** @description Validation failed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description You are a member, but your role is below what this route requires. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description No such household, OR you are not a member of it. Deliberately indistinguishable. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    HouseholdsController_listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseholdMemberView"][];
                };
            };
            /** @description Validation failed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description You are a member, but your role is below what this route requires. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description No such household, OR you are not a member of it. Deliberately indistinguishable. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    HouseholdsController_addMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddHouseholdMemberRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseholdMemberView"];
                };
            };
            /** @description Validation failed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description You are a member, but your role is below what this route requires. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description No such household, OR you are not a member of it. Deliberately indistinguishable. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Already a member, or that person is already linked. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    HouseholdsController_leave: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Left. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description You are a member, but your role is below what this route requires. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description No such household, OR you are not a member of it. Deliberately indistinguishable. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description You are the last planner. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    HouseholdsController_updateOwnMembership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOwnMembershipRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseholdMemberView"];
                };
            };
            /** @description Validation failed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description You are a member, but your role is below what this route requires. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description No such household, OR you are not a member of it. Deliberately indistinguishable. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description That person is already linked to another member. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    HouseholdsController_removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
                memberId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description You are a member, but your role is below what this route requires. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description No such household, OR you are not a member of it. Deliberately indistinguishable. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Would leave the household with no planner. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    HouseholdsController_updateMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
                memberId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateHouseholdMemberRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseholdMemberView"];
                };
            };
            /** @description Validation failed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description You are a member, but your role is below what this route requires. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description No such household, OR you are not a member of it. Deliberately indistinguishable. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Would leave the household with no planner. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    MeController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation failed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
}
