// GENERATED — never hand-edit.
// Source: services/solver/mealplan/schemas.py + service.py via openapi.json.
// Regenerate: make contracts (or: npm run gen). CI gate: npm run check.
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/solve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Solve
         * @description Validated library in → WeekPlanResult out. Thin orchestration of the
         *     exact pipeline the CLI runs: load → choose_menu (or explicit menu) →
         *     build_week → session_plan → purchase/cost. No solver logic lives here.
         */
        post: operations["solve_solve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AblationEntry
         * @description doctor structural ablation, per person: how many lean mains the week
         *     actually needs (None = stays feasible no matter which mains are cut).
         */
        AblationEntry: {
            /** Min Lean Mains */
            min_lean_mains: number | null;
            /** Miss */
            miss: {
                [key: string]: number;
            };
        };
        /**
         * BindingMacro
         * @description engine.binding_macro: WHICH macro binds for a person on this library.
         */
        BindingMacro: {
            /** At Tolerance */
            at_tolerance: number;
            /**
             * Direction
             * @enum {string}
             */
            direction: "over" | "short";
            /** Macro */
            macro: string;
            /** Misses */
            misses: {
                [key: string]: number;
            };
            /** Signed Miss G */
            signed_miss_g: number;
        };
        /**
         * CarbHeadroom
         * @description engine.carb_headroom: per-day carb availability vs target, per person.
         */
        CarbHeadroom: {
            /** Ok */
            ok: boolean;
            /** Per Day */
            per_day: components["schemas"]["CarbHeadroomDay"][];
            /** Target G */
            target_g: number;
            /** Worst Day */
            worst_day: number | null;
            /** Worst Headroom G */
            worst_headroom_g: number;
        };
        /** CarbHeadroomDay */
        CarbHeadroomDay: {
            /** Day */
            day: number;
            /** Headroom G */
            headroom_g: number;
        };
        /** CookSession */
        CookSession: {
            /** Batches */
            batches: {
                [key: string]: number;
            };
            /** Demand G */
            demand_g: {
                [key: string]: number;
            };
            /** Freezer Notes */
            freezer_notes: components["schemas"]["FreezerServe"][];
            /** Index */
            index: number;
            /** Made G */
            made_g: {
                [key: string]: number;
            };
            /** Minutes */
            minutes: number;
            /** Start */
            start: number;
            /** Thaw Notes */
            thaw_notes: components["schemas"]["ThawNote"][];
        };
        /**
         * CostBlock
         * @description costing.menu_cost + attribute + budget_ceiling, composed.
         */
        CostBlock: {
            /** Ceiling */
            ceiling: number | null;
            /** Eaten Value */
            eaten_value: {
                [key: string]: number;
            };
            /** Groceries */
            groceries: number;
            /** Shares */
            shares: {
                [key: string]: number;
            };
        };
        /**
         * DoctorReport
         * @description Mirror of engine.doctor's structured ``data`` (the second element of
         *     its (text, data) return). ``raw_freshness`` is present only when doctor
         *     ran with ingredient data (``ing`` passed).
         */
        DoctorReport: {
            /** Binding Macro */
            binding_macro: {
                [key: string]: components["schemas"]["BindingMacro"] | null;
            };
            /** Carb Headroom */
            carb_headroom: {
                [key: string]: components["schemas"]["CarbHeadroom"];
            };
            /** Feasibility */
            feasibility: {
                [key: string]: components["schemas"]["FeasibilityEntry"];
            };
            lean_coverage: components["schemas"]["LeanCoverage"];
            /**
             * Raw Freshness
             * @default null
             */
            raw_freshness: components["schemas"]["RawFreshnessIssue"][] | null;
            structural: components["schemas"]["StructuralCheck"];
            /** Volume Floor */
            volume_floor: {
                [key: string]: components["schemas"]["VolumeFloor"];
            };
        };
        /**
         * FeasibilityEntry
         * @description doctor feasibility, per person.
         */
        FeasibilityEntry: {
            /** Blocked */
            blocked: string[];
            /** Clears At Tolerance */
            clears_at_tolerance: number | null;
            /** Eligible */
            eligible: number;
            /** Miss */
            miss: {
                [key: string]: number;
            };
            /** Ok */
            ok: boolean;
            /** Total */
            total: number;
        };
        /**
         * FreezerServe
         * @description Demand fed from the freezer bridge — thaw ahead (M0.5).
         */
        FreezerServe: {
            /** Component */
            component: string;
            /** Day */
            day: number;
            /** Grams */
            grams: number;
            /** Note */
            note: string;
            /** Session */
            session: number;
        };
        /** Healthz */
        Healthz: {
            /** Api Version */
            api_version: string;
            /** Ok */
            ok: boolean;
        };
        /**
         * LeanCoverage
         * @description engine.lean_coverage: the REAL shelf-life stagger check.
         */
        LeanCoverage: {
            /** Lean Anchors */
            lean_anchors: string[];
            /** Per Day */
            per_day: {
                [key: string]: string[];
            };
            /** Uncovered Days */
            uncovered_days: number[];
        };
        /**
         * LeftoverServe
         * @description Demand fed from cooked pantry leftovers — already paid for (M1.8).
         */
        LeftoverServe: {
            /** Component */
            component: string;
            /** Day */
            day: number;
            /** Grams */
            grams: number;
            /** Note */
            note: string;
        };
        /**
         * LibraryIdentity
         * @description Which library produced this plan: a canonical-JSON sha256 over the
         *     three inline documents plus human-oriented counts. Reproducibility is
         *     seed + library identity (PRD §8.3 determinism).
         */
        LibraryIdentity: {
            /** Digest Sha256 */
            digest_sha256: string;
            /** N Components */
            n_components: number;
            /** N Ingredients */
            n_ingredients: number;
            /** Name */
            name?: string | null;
            /** People */
            people: string[];
        };
        /**
         * MenuInfo
         * @description Mirror of score_menu's info dict (returned through choose_menu).
         */
        MenuInfo: {
            /** Active Min */
            active_min: number;
            /** Cuisines */
            cuisines: number;
            /** Roles */
            roles: {
                [key: string]: number;
            };
            /** Waste Perishable */
            waste_perishable: number;
        };
        /**
         * PlateResult
         * @description Mirror of engine.PlateResult — (ok, {id: grams}, {macro: signed_miss})
         *     plus ``.warnings``. Misses are signed: positive = forced OVER target,
         *     negative = cannot REACH target (M1.0).
         */
        PlateResult: {
            /** Misses */
            misses: {
                [key: string]: number;
            };
            /** Ok */
            ok: boolean;
            /** Portions */
            portions: {
                [key: string]: number;
            };
            /** Warnings */
            warnings?: components["schemas"]["StructuredWarning"][];
        };
        /**
         * RawBlocker
         * @description One perishable, non-freezable ingredient past raw keeps_days at cook
         *     time (costing.raw_freshness blocker entry).
         */
        RawBlocker: {
            /** Ingredient */
            ingredient: string;
            /** Keeps Days */
            keeps_days: number;
            /** Shop Day */
            shop_day: number | null;
        };
        /**
         * RawFreshnessIssue
         * @description doctor: (component, session) pair the raw-freshness rule blocks.
         */
        RawFreshnessIssue: {
            /** Blockers */
            blockers: components["schemas"]["RawBlocker"][];
            /** Component */
            component: string;
            /** Day */
            day: number;
            /** Session */
            session: number;
        };
        /**
         * SessionPlan
         * @description Mirror of costing.session_plan's return dict.
         */
        SessionPlan: {
            /** Batches */
            batches: {
                [key: string]: number;
            };
            /** Freezer */
            freezer: components["schemas"]["FreezerServe"][];
            /** Leftover */
            leftover: components["schemas"]["LeftoverServe"][];
            /** Minutes */
            minutes: number;
            /** Sessions */
            sessions: components["schemas"]["CookSession"][];
            /** Unattributed */
            unattributed: components["schemas"]["UnattributedDemand"][];
        };
        /**
         * ShoppingRow
         * @description Mirror of one costing.purchase row — engine-side it is the 7-tuple
         *     ``(name, need_g, units, pack_g, leftover_g, perishable, keeps_days)``;
         *     the positional mapping lives here and nowhere else.
         */
        ShoppingRow: {
            /** Ingredient */
            ingredient: string;
            /** Keeps Days */
            keeps_days: number;
            /** Leftover G */
            leftover_g: number;
            /** Need G */
            need_g: number;
            /** Pack G */
            pack_g: number;
            /** Perishable */
            perishable: boolean;
            /** Units */
            units: number;
        };
        /**
         * SolveOptions
         * @description Options mirroring the CLI's knobs (subset — the spike's scope).
         */
        SolveOptions: {
            /** Menu */
            menu?: string[] | null;
            /** Must */
            must?: string[];
            /**
             * N
             * @default 12
             */
            n: number;
            /**
             * Seed
             * @default 0
             */
            seed: number;
        };
        /**
         * SolveRequest
         * @description Inline library documents (the YAML interchange documents, as JSON) +
         *     options. Validation happens through the engine's own io_yaml validators —
         *     the service adds none of its own rules.
         */
        SolveRequest: {
            /** Components */
            components: {
                [key: string]: unknown;
            };
            /** Ingredients */
            ingredients: {
                [key: string]: unknown;
            };
            /** Library Name */
            library_name?: string | null;
            options?: components["schemas"]["SolveOptions"];
            /** People */
            people: {
                [key: string]: unknown;
            };
        };
        /** StructuralCheck */
        StructuralCheck: {
            /** Ablation */
            ablation: {
                [key: string]: components["schemas"]["AblationEntry"];
            };
            /** Dense Carriers */
            dense_carriers: number;
            /** Lean Anchors */
            lean_anchors: string[];
        };
        /**
         * StructuredWarning
         * @description One structured engine warning. ``code`` + ``message`` are universal;
         *     every other key is code-specific payload (pin_adjusted carries bounds,
         *     stock_expiring_unused carries grams/ages, …) — mirrored open, on purpose.
         */
        StructuredWarning: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * ThawNote
         * @description Frozen-on-arrival ingredient to thaw before a session (M0.6).
         */
        ThawNote: {
            /** Component */
            component: string;
            /** Ingredient */
            ingredient: string;
            /** Note */
            note: string;
            /** Session */
            session: number;
            /** Shop Day */
            shop_day: number;
        };
        /**
         * UnattributedDemand
         * @description Demand no cook session can feed — reported, never invented.
         */
        UnattributedDemand: {
            /** Component */
            component: string;
            /** Day */
            day: number;
            /** Grams */
            grams: number;
        };
        /**
         * ValidationErrorResponse
         * @description 422 body: EVERY issue found (io_yaml.ValidationError), never the first.
         */
        ValidationErrorResponse: {
            /**
             * Detail
             * @default library failed validation
             */
            detail: string;
            /** Issues */
            issues: components["schemas"]["ValidationIssue"][];
        };
        /**
         * ValidationIssue
         * @description Mirror of io_yaml.ValidationIssue: one problem, precisely located.
         */
        ValidationIssue: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Severity
             * @default error
             * @enum {string}
             */
            severity: "error" | "warning";
            /** Where */
            where: string;
        };
        /**
         * VolumeBlock
         * @description Per-person daily food mass over the week's non-empty days.
         */
        VolumeBlock: {
            /** Avg G */
            avg_g: number;
            /** Cap G */
            cap_g: number | null;
            /** Max G */
            max_g: number;
            /** Min G */
            min_g: number;
        };
        /**
         * VolumeFloor
         * @description engine.volume_floor: minimum daily food mass the targets require.
         */
        VolumeFloor: {
            binding: components["schemas"]["VolumeFloorBinding"] | null;
            /** Floor G */
            floor_g: number | null;
            /** Note */
            note: string | null;
            /** Searched */
            searched: number[];
        };
        /** VolumeFloorBinding */
        VolumeFloorBinding: {
            /**
             * Direction
             * @enum {string}
             */
            direction: "over" | "short";
            /** Macro */
            macro: string;
            /** Signed Miss G */
            signed_miss_g: number;
        };
        /**
         * WeekPlanResult
         * @description The /solve response: the full pipeline's outputs, verbatim (P10 — the
         *     engine is the sole producer; this model only names what it returned).
         */
        WeekPlanResult: {
            /**
             * Api Version
             * @default mealplan/v2
             * @constant
             */
            api_version: "mealplan/v2";
            /** Broke */
            broke: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            cost: components["schemas"]["CostBlock"];
            /** Demand */
            demand: {
                [key: string]: number;
            };
            /** Feasible */
            feasible: boolean;
            library: components["schemas"]["LibraryIdentity"];
            /** Menu */
            menu: string[];
            menu_info: components["schemas"]["MenuInfo"];
            /** Relax Tiers */
            relax_tiers: {
                [key: string]: (number | null)[];
            };
            /** Seed */
            seed: number;
            session_plan: components["schemas"]["SessionPlan"];
            /** Shopping */
            shopping: components["schemas"]["ShoppingRow"][];
            /** Volume */
            volume: {
                [key: string]: components["schemas"]["VolumeBlock"];
            };
            /** Waste Perishable G */
            waste_perishable_g: number;
            /** Waste Total G */
            waste_total_g: number;
            /** Weeks */
            weeks: {
                [key: string]: {
                    [key: string]: number;
                }[];
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Healthz"];
                };
            };
        };
    };
    solve_solve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeekPlanResult"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
}
