-- Households, membership, and the audit trail.
--
-- Sections:
--   1. Tables, enums, indexes  — generated by `prisma migrate diff` (do not hand-edit)
--   2. auth.users foreign key  — conditional; Supabase-only
--   3. RLS safety net          — ARCHITECTURE.md: "dumb household_id policies
--                                underneath Nest; NEVER business logic"
--
-- Sections 2 and 3 are hand-written and re-emitted verbatim by
-- scripts/new-migration.sh when the model changes; they live here because a
-- schema without its isolation boundary is a schema that shipped half-done.

-- ---------------------------------------------------------------------------
-- 1. Tables (generated)
-- ---------------------------------------------------------------------------

-- CreateEnum
CREATE TYPE "household_role" AS ENUM ('planner', 'cook', 'eater');

-- CreateTable
CREATE TABLE "households" (
    "id" UUID NOT NULL,
    "name" VARCHAR(120) NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "households_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "household_members" (
    "id" UUID NOT NULL,
    "household_id" UUID NOT NULL,
    -- NULL while this member is a placeholder (a real member with no account
    -- yet). See schema.prisma for the claim seam this nullability exists for.
    "user_id" UUID,
    "role" "household_role" NOT NULL,
    "display_name" VARCHAR(120) NOT NULL,
    "person_name" VARCHAR(64),
    "invite_email" VARCHAR(320),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "household_members_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "household_audit_log" (
    "id" UUID NOT NULL,
    "household_id" UUID NOT NULL,
    "actor_user_id" UUID NOT NULL,
    "action" VARCHAR(64) NOT NULL,
    "target_id" UUID,
    "detail" JSONB,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "household_audit_log_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "household_members_user_id_idx" ON "household_members"("user_id");

-- CreateIndex
-- NULLS DISTINCT (the Postgres default) is load-bearing here, not incidental:
-- it lets a household hold many placeholder members while still preventing one
-- account from joining the same household twice, which is what makes claiming
-- a safe UPDATE. Switching this to NULLS NOT DISTINCT would cap a household at
-- one placeholder.
CREATE UNIQUE INDEX "household_members_household_user_key" ON "household_members"("household_id", "user_id");

-- CreateIndex
CREATE UNIQUE INDEX "household_members_household_person_key" ON "household_members"("household_id", "person_name");

-- CreateIndex
CREATE INDEX "household_audit_log_household_created_idx" ON "household_audit_log"("household_id", "created_at");

-- AddForeignKey
ALTER TABLE "household_members" ADD CONSTRAINT "household_members_household_id_fkey" FOREIGN KEY ("household_id") REFERENCES "households"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- NOTE: household_audit_log has NO foreign keys, by design (schema.prisma).
-- An audit trail that cascade-deletes with the household it audits cannot
-- record that the household was deleted.

-- ---------------------------------------------------------------------------
-- 2. auth.users foreign key (Supabase stacks only)
-- ---------------------------------------------------------------------------
-- household_members.user_id points at GoTrue's auth.users. Prisma does not
-- model that table (it is GoTrue's, not ours), so the constraint is added
-- here. Guarded because the same migration must apply to a bare Postgres —
-- CI and the PGlite test harness have no auth schema, and the column is a
-- plain uuid there.
--
-- ON DELETE CASCADE: deleting an account removes its memberships. The audit
-- trail deliberately does NOT cascade (see schema.prisma) — the record of who
-- did what outlives the account.

DO $$
BEGIN
  IF to_regclass('auth.users') IS NOT NULL THEN
    ALTER TABLE "household_members"
      ADD CONSTRAINT "household_members_user_id_fkey"
      FOREIGN KEY ("user_id") REFERENCES auth.users("id")
      ON DELETE CASCADE ON UPDATE CASCADE;
  ELSE
    RAISE NOTICE 'auth.users absent (bare Postgres) — household_members.user_id left unconstrained';
  END IF;
END $$;

-- ---------------------------------------------------------------------------
-- 3. RLS safety net
-- ---------------------------------------------------------------------------
-- READ THIS BEFORE CHANGING ANYTHING BELOW.
--
-- Authorization for this product lives in NestJS (ARCHITECTURE.md, "one
-- brain"). These policies are NOT that. They are a containment boundary for
-- every path that reaches Postgres WITHOUT going through Nest — a leaked
-- publishable key, a stray PostgREST request, a future Supabase client in the
-- web app. Nest connects as the table owner and is unaffected by them
-- (Postgres exempts owners from RLS unless FORCE ROW LEVEL SECURITY is set,
-- which we deliberately do not set).
--
-- Consequences, stated so nobody has to rediscover them:
--   * Deleting these policies does not change one line of API behaviour. If it
--     did, business logic would have leaked into the database and that is the
--     bug.
--   * The policies are membership-only. There is no planner/cook/eater logic
--     here, and there must never be — the role ladder is Nest's job.
--   * There are NO write policies. Every non-owner write is denied outright.
--     Writes go through the API, which is the only thing that records audit.

-- auth.uid() reads the JWT claim GUCs that PostgREST sets per request. This
-- function reads exactly the same GUCs rather than calling auth.uid(), so the
-- migration applies unchanged to a bare Postgres — which is what lets the RLS
-- tests run for real against PGlite instead of being asserted by eyeball.
--
-- Malformed input resolves to "no subject" rather than raising. Both casts
-- here can fail on attacker-influenced data — `''::jsonb` on an empty claims
-- GUC, and `'admin'::uuid` on a subject that is not a UUID — and a policy that
-- raises instead of returning false turns a denied read into a 500 and makes
-- the function a probe for what the caller controls. Returning NULL denies,
-- because NULL never equals a stored user_id.
CREATE OR REPLACE FUNCTION public.current_user_id()
RETURNS uuid
LANGUAGE plpgsql
STABLE
SET search_path = ''
AS $$
DECLARE
  claimed text;
BEGIN
  claimed := COALESCE(
    NULLIF(current_setting('request.jwt.claim.sub', true), ''),
    NULLIF(current_setting('request.jwt.claims', true), '')::jsonb ->> 'sub'
  );
  RETURN NULLIF(claimed, '')::uuid;
EXCEPTION WHEN others THEN
  RETURN NULL;
END;
$$;

COMMENT ON FUNCTION public.current_user_id() IS
  'Current request''s auth.users id from the JWT claim GUCs. Mirrors auth.uid() without depending on the auth schema. Used only by the RLS safety net.';

-- SECURITY DEFINER breaks the self-reference: a policy on household_members
-- that queried household_members directly would recurse forever. The function
-- can only ever answer a question about the CALLER's own membership, so it
-- leaks nothing.
CREATE OR REPLACE FUNCTION public.is_household_member(hid uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.household_members m
    WHERE m.household_id = hid
      AND m.user_id = public.current_user_id()
  )
$$;

COMMENT ON FUNCTION public.is_household_member(uuid) IS
  'True when the current JWT subject is a member of the household. SECURITY DEFINER to avoid RLS recursion on household_members. Safety net only — never call from application code.';

ALTER TABLE "households" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "household_members" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "household_audit_log" ENABLE ROW LEVEL SECURITY;

-- (SELECT public.current_user_id()) rather than a bare call: Postgres hoists
-- the scalar subquery to an InitPlan and evaluates it once per query instead
-- of once per row.
CREATE POLICY "households_member_select" ON "households"
  FOR SELECT USING (public.is_household_member("id"));

CREATE POLICY "household_members_member_select" ON "household_members"
  FOR SELECT USING (public.is_household_member("household_id"));

CREATE POLICY "household_audit_log_member_select" ON "household_audit_log"
  FOR SELECT USING (public.is_household_member("household_id"));

-- Data API roles. `anon` gets nothing at all: an unauthenticated caller has no
-- business seeing that a household exists. `authenticated` gets SELECT only,
-- which the policies above then narrow to its own households. Guarded because
-- these roles exist on Supabase and not on a bare Postgres.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    REVOKE ALL ON TABLE "households", "household_members", "household_audit_log" FROM anon;
  END IF;

  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    REVOKE ALL ON TABLE "households", "household_members", "household_audit_log" FROM authenticated;
    GRANT SELECT ON TABLE "households", "household_members", "household_audit_log" TO authenticated;
  END IF;
END $$;
